output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400
    - N802  # function name should be lowercase, breaks on tests
    - N803
  options:
    max-line-length: 80

pyflakes:
  disable:
    - F999

pylint:
  disable:
    - too-few-public-methods
    - invalid-name
    - no-self-use
    - no-member
    - abstract-method
    - logging-not-lazy
    - arguments-differ
  options:
    max-line-length: 80

dodgy:
  run: true

ignore-paths:
  - node_modules
  - venv
  - env
  - .env
  - .venv
  - .envrc
  - .coveragerc
  - infra
  - image
  - entrypoints
  - conf
  - .github
  - templates
  - .direnv
  - alia/settings.py
  - manage.py

ignore-patterns:
  - .+/migrations/.+
  - .+/settings/.+
  - alia/settings.py
  - manage.py
